@url_dev=http://localhost:3001/v1/api/

### signup
POST {{url_dev}}/shop/signup

content-type: application/json

# {
#     "name": "sample",
#     "email": "cuongbn@gmail",
#     "password": "123456",

# }